### ISSUE TITLE
Gnome 3.14 compatibility

### ISSUE THREAD

**Issue by torpet** [maweki/twitchlive-extension#23] opened 2016-06-08 00:18 UTC
Is it possible to backport this so it supports Gnome 3.14? I am on Debian 8 on my laptop and would like to use this extension a lot.

edit: initial thread title said Gnome 3.16 compatibility.

**Comment by RaphaelRochet** [comment] 2016-06-08 06:54
It should already support 3.16. What issue are you facing when trying to install from extensions.gnome.org ?

**Comment by maweki** [comment] 2016-06-08 08:22
I think Debian Jessie comes with 3.14. I will enable it for the next version but I don't really have a chance to test it.

The review process on extensions.gnome.org might take a week or two so I'll comment here once the next version of the twitchlive extension is available.

**Comment by RaphaelRochet** [comment] 2016-06-08 08:27
We could also attach a zip here so @torpet can test it
There was API changes in gnome-shell, we'd better check it's of before uploading on ego.

**Comment by torpet** [comment] 2016-06-08 08:32
Sorry, indeed I got the version wrong. Debian 8 is on Gnome 3.14.1, not 3.16.
When I am trying to install it from e.g.o., it simply doesn't do anything, meaning it won't show up in the list of installed extentions.

If you attach a zip here I will gladly test it.

**Comment by maweki** [comment] 2016-06-08 08:32
> we'd better check it's of before uploading on ego

But what if we really are the best, greatest, and brightest? ;)

Yeah, sure. I merge #22 and create a 3-14-compat-branch in a few minutes.

**Comment by maweki** [comment] 2016-06-08 08:41
@torpet you can download a zip or clone from here: https://github.com/maweki/twitchlive-extension/archive/3-14-compat.zip

Just make sure the folder where the code (extension.js and metadata.js and stuff is), is located in and renamed to `~/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de`. Please let us know what you find out as soon as possible. We want to create a new release for extensions.gnome.org soon-ish and I'd like to include the 3.14 support if it isn't too too much work.

**Comment by torpet** [comment] 2016-06-08 09:46
Installation works fine, configuring the extension as well. But after adding some streamers to the list, it keeps saying "Updating ..." forever. Can I help you debug the extension somehow?

**Comment by maweki** [comment] 2016-06-08 09:56
It's hard to debug extensions in general. The best thing is, to type into the terminal `journalctl --user --follow` and look for exceptions or error messages in gnome-shell or soup (they probably won't be marked as twitchlive). You might have to restart gnome-shell (alt+f2 and then `r`) in order to reset the extension, once an exception happened.

If you seen anything (maybe `soandso is not a function`), we have a hint on what's not working and follow up.

**Comment by torpet** [comment] 2016-06-08 11:53
I tried to debug it, but I couldn't get any info. All it does is saying "Updating ...". Do you want me to peek around in the code this evening or will you have a chance to get a Debian VM running?

**Comment by maweki** [comment] 2016-06-08 12:04
@torpet Feel free to take a look and try for yourself. For us it might take some time to get a proper environment running.

I don't know how much experience you have with gnome-shell debugging but in my experience, adding a lot of `log` messages and seeing, which ones do not get executed is a good way to get an idea about where the problem is. I know it's a pain in the ... but there's sadly, as far as I know, no better tooling.

**Comment by torpet** [comment] 2016-06-08 12:12
@maweki I am slightly familiar with JS, but not directly with gnome extensions. I think I will find my way around it.

**Comment by maweki** [comment] 2016-06-08 12:34
@torpet That's great, thank you. To get started, you might want to take a look here
https://wiki.gnome.org/Projects/GnomeShell/Extensions (there's a bit about debugging at the end)

This is slightly more extensive but maybe not all in scope of what you're hunting for:
https://wiki.gnome.org/Projects/GnomeShell/Extensions/StepByStepTutorial

**Comment by torpet** [comment] 2016-06-08 20:02
Funnily enough the plugin stopped working for me even on openSUSE (Gnome 3.18). Did Twitch change the API?
Testing this new on my Arch machine.

**Comment by maweki** [comment] 2016-06-08 20:14
> Did Twitch change its API?

No, it hasn't and the simple public (no oauth and stuff) API is quite robust from what I've seen.

**Comment by torpet** [comment] 2016-06-08 20:28
Working fine on Arch. This is indeed weird. What distro do you develop this extension on?

**Comment by maweki** [comment] 2016-06-08 20:30
I am on Fedora while @RaphaelRochet lives in Arch-Land. But as far as I know, only the gnome version and maybe some theme package *should* affect the extension at all.

**Comment by torpet** [comment] 2016-06-08 21:11
Found the issue. One of those 2 extensions [1] & [2] (or both), which were written by the same author, caused all of my gnome extensions in the tray to have network problems. The imgur or radio extension didn't work either.

[1] https://extensions.gnome.org/extension/904/disconnect-wifi/
[2] https://extensions.gnome.org/extension/905/refresh-wifi-connections/

The extensions were both installed on my Debian and openSUSE machines, but not on my Arch machine. That explains why it only worked on Arch.

I will give your 3.14-compat-zip another try now.

**Comment by torpet** [comment] 2016-06-08 23:25
Not working on Debian 8 vanilla installation. See attached screenshots.

![screenshot from 2016-06-09 01 25 03](https://cloud.githubusercontent.com/assets/4422076/15914413/0971a6f6-2de1-11e6-91f8-82a127e8e7fd.png)
![screenshot from 2016-06-09 01 25 08](https://cloud.githubusercontent.com/assets/4422076/15914414/099c429e-2de1-11e6-8650-9b2c629083a5.png)

**Comment by maweki** [comment] 2016-06-09 08:49
And there's nothing in the user's journal?

Okay, thank you. I guess I'll have to try it myself. I've already downloaded the install image but I am a bit busy the next few days. Feel free to add any additional information you happen to gather.

**Comment by torpet** [comment] 2016-06-10 16:02
Nope, nothing at all. In fact I am being told that the user journal is empty. Will keep you updated.

**Comment by maweki** [comment] 2016-06-11 21:10
So, I've got a VM running and the first issue I came across was the following:

`Jun 11 23:09:01 debiantest gnome-session[905]: Gjs-Message: JS LOG: An error occured : Error: No property fallback_icon_name on this GObject StIcon
`

**Comment by RaphaelRochet** [comment] 2016-06-11 21:40
@torpet Could you give a new try ?
( same download url : https://github.com/maweki/twitchlive-extension/archive/3-14-compat.zip )

**Comment by maweki** [comment] 2016-06-14 16:16
The version with 3.14 support is now available at extensions.gnome.org. My preliminary tests showed, that this version works at least under Debian 8. Should any other issues arise, feel free to open a new ticket.

**Closed by maweki** 2016-06-14 16:16 UTC

**Comment by torpet** [comment] 2016-06-18 11:41
It is working fine now, thanks for the great work!
